/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSwitch: typeof import('./src/components/app-switch.vue')['default']
    BaseCardDrawer: typeof import('./src/components/base-card-drawer.vue')['default']
    BaseDataTable: typeof import('./src/components/base-data-table.vue')['default']
    Dialog: typeof import('./src/components/reports/dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LightSwitch: typeof import('./src/components/light-switch.vue')['default']
    List: typeof import('./src/components/reports/list.vue')['default']
    QuickSwitch: typeof import('./src/components/quick-switch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchWithChips: typeof import('./src/components/search-with-chips.vue')['default']
  }
}
